### ISSUE TITLE
在组件中无法找到 Optimization Guide On Device Model

### ISSUE THREAD

**Issue by AZhanGGGGG** [kongxiangyiren/window-ai#1]
![截图chrome](https://github.com/user-attachments/assets/b67f966b-f94f-438a-b786-d61dd3405562)
在组件中无法找到 Optimization Guide On Device Model

**Comment by kongxiangyiren** [comment]
需要谷歌浏览器 128 版本，更新谷歌浏览器到最新版本，然后重启，还没有的话下载chrome dev 版本试试 https://www.google.cn/intl/zh-CN/chrome/dev/next-steps.html
